name: "CI:LintAndTest"

on: [pull_request]

jobs:
  run-phpunit:
    runs-on: ubuntu-latest
    container:
      image:  prooph/composer:7.4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install vendors
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Lint php
        run: composer lint:php
      - name: Unit tests
        run: composer tests