name: "CI:LintAndTest"

on:
  - pull_request
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP box
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: phive
      - name: Show setup
        run: php -v && phive version && composer --version
      - name: Install vendors
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E,31C7E470E2138192,4AA394086372C20A
      - name: Lint php
        run: composer lint:php
      - name: Unit tests
        run: composer tests